version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
      
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 100000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 100000000

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      
  db:
    image: mysql:5.7
    
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_dsbd
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
    - ./Database.sql:/docker-entrypoint-initdb.d/Database.sql
    restart: always

  data_pipeline:
    build:
      context: ./data_pipeline
      dockerfile: Dockerfile
    depends_on:
      - prometheus
      - kafka
    environment:
      - PROMETHEUS_URL=http://15.160.61.227:29090
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC= 'prometheusdata'
      
  data_storage:
    build:
      context: ./data_storage
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - db
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=test_dsbd