FROM python:3.10

RUN pip install grpcio
RUN pip install grpcio-tools
RUN pip install mysql-connector-python

ENV MYSQL_HOST localhost
ENV MYSQL_USER user
ENV MYSQL_PASSWORD password
ENV MYSQL_DB test_dsbd





