# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: retrieval.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fretrieval.proto\x12\rdataretrieval\"!\n\x10RetrievalRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\xb8\x01\n\x15RetrievalDickeyFuller\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tpartition\x18\x02 \x01(\t\x12\x16\n\x0etest_statistic\x18\x03 \x01(\x02\x12\x0f\n\x07p_value\x18\x04 \x01(\x02\x12\x15\n\ris_stationary\x18\x05 \x01(\x08\x12\x13\n\x0b\x63rit_value1\x18\x06 \x01(\x02\x12\x13\n\x0b\x63rit_value5\x18\x07 \x01(\x02\x12\x14\n\x0c\x63rit_value10\x18\x08 \x01(\x02\"m\n\x16RetrievalDecomposition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tpartition\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x10\n\x08typology\x18\x04 \x01(\t\x12\r\n\x05value\x18\x05 \x01(\x02\"]\n\x18RetrievalHodrickPrescott\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tpartition\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x02\"J\n\x18RetrievalAutocorrelation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tpartition\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x02\"\x7f\n\x13RetrievalAggregates\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tpartition\x18\x02 \x01(\t\x12\r\n\x05range\x18\x03 \x01(\t\x12\x10\n\x08typology\x18\x04 \x01(\t\x12\r\n\x05value\x18\x05 \x01(\x02\x12\x17\n\x0fpredicted_value\x18\x06 \x01(\x02\x32\xf4\x03\n\x10RetrievalService\x12Z\n\x0fGetDickeyFuller\x12\x1f.dataretrieval.RetrievalRequest\x1a$.dataretrieval.RetrievalDickeyFuller\"\x00\x12_\n\x11ListDecomposition\x12\x1f.dataretrieval.RetrievalRequest\x1a%.dataretrieval.RetrievalDecomposition\"\x00\x30\x01\x12\x63\n\x13ListHodrickPrescott\x12\x1f.dataretrieval.RetrievalRequest\x1a\'.dataretrieval.RetrievalHodrickPrescott\"\x00\x30\x01\x12\x63\n\x13ListAutocorrelation\x12\x1f.dataretrieval.RetrievalRequest\x1a\'.dataretrieval.RetrievalAutocorrelation\"\x00\x30\x01\x12Y\n\x0eListAggregates\x12\x1f.dataretrieval.RetrievalRequest\x1a\".dataretrieval.RetrievalAggregates\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'retrieval_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RETRIEVALREQUEST._serialized_start=34
  _RETRIEVALREQUEST._serialized_end=67
  _RETRIEVALDICKEYFULLER._serialized_start=70
  _RETRIEVALDICKEYFULLER._serialized_end=254
  _RETRIEVALDECOMPOSITION._serialized_start=256
  _RETRIEVALDECOMPOSITION._serialized_end=365
  _RETRIEVALHODRICKPRESCOTT._serialized_start=367
  _RETRIEVALHODRICKPRESCOTT._serialized_end=460
  _RETRIEVALAUTOCORRELATION._serialized_start=462
  _RETRIEVALAUTOCORRELATION._serialized_end=536
  _RETRIEVALAGGREGATES._serialized_start=538
  _RETRIEVALAGGREGATES._serialized_end=665
  _RETRIEVALSERVICE._serialized_start=668
  _RETRIEVALSERVICE._serialized_end=1168
# @@protoc_insertion_point(module_scope)
